var ex_411 = new Array();
ex_411.push("setIntr(\"<b>今回の挑戦状を解くには「繰り返し」が必要にゃ！<br>ということでこのコードを見るにゃ。<br>このコードは「こん」と「たぬ」をそれぞれ２回ずつ<br>出力するプログラムにゃ。</b>\");;baON()");

ex_411.push("baOFF();;line(3);;ANIME_changeSPEED_Ex(1.5);;ANIME_sengen(\"int\",\"a\");;line(4);;ANIME_sengen(\"int\",\"b\");;line(5);;ANIME_dainyu(\"a\",\"1\");;ANIME_compare([\"a<=2\"],[\"true\"],true);;line(6);;ANIME_printf(\"こん\\n\");;setPrintf(\"こん\\n\");;line(5);;ANIME_enzan_dainyu(\"a\",\"a+1\",\"2\");;ANIME_compare([\"a<=2\"],[\"true\"],true);;line(6);;ANIME_printf(\"こん\\n\");;setPrintf(\"こん\\n\");;line(5);;ANIME_enzan_dainyu(\"a\",\"a+1\",\"3\");;ANIME_compare([\"a<=2\"],[\"false\"],false);;line(8);;ANIME_dainyu(\"b\",\"2\");;ANIME_compare([\"b>=1\"],[\"true\"],true);;line(9);;ANIME_printf(\"たぬ\\n\");;setPrintf(\"たぬ\\n\");;line(8);;ANIME_enzan_dainyu(\"b\",\"b-1\",\"1\");;ANIME_compare([\"b>=1\"],[\"true\"],true);;line(9);;ANIME_printf(\"たぬ\\n\");;setPrintf(\"たぬ\\n\");;line(8);;ANIME_enzan_dainyu(\"b\",\"b-1\",\"0\");;ANIME_compare([\"b>=1\"],[\"false\"],false);;line(11);;biON();;setIntr(\"<b>では、まずは4，5，6行目を見るにゃ</b>\")");

ex_411.push("line_reset();;line(5);;setIntr(\"<b>これは<font color=#ff0000>for</font>文というもので、</br>あるコードを繰り返し実行したい時につかうにゃ<br>今回は「こん」や「たぬ」の出力を繰り返してるのがわかるかにゃ？</b>\")");
ex_411.push("setIntr(\"<b>『()』で囲まれた『a=1』の部分を<font color=#ff0000>初期化式</font></br>『a<=3』の部分を<font color=#ff0000>継続条件式</font></br>『a++』の部分を<font color=#ff0000>再初期化式</font>というにゃ。</br>『{}』で囲まれた部分を<font color=#ff0000>文</font>というにゃ</br></b>\")");
ex_411.push("setIntr(\"<b>初期化式はfor文の1行目についたときに実行されるにゃ</br>今回はaに1を代入してるにゃ</b>\")");
ex_411.push("setIntr(\"<b>そして、継続条件式が満たされていたら文を実行するにゃ</br>ちなみに条件が満たされていることを「<font color=#ff0000>真</font>」というにゃ</b>\")");
ex_411.push("setIntr(\"<b>今回は継続条件式がa<=2だから、aが2以下のあいだが真にゃ</br>今aには１が代入されているから真なので、</br>文が実行されて「こん」と出力してるにゃ</b>\")");
ex_411.push("setIntr(\"<b>そして、文の実行が終わるとfor文の1行目に戻って</br>再初期化式を実行するにゃ</br>今回はa++を実行するにゃ</b>\")");
ex_411.push("setIntr(\"<b>そして、継続条件式が満たされていたら</br>もう一度文が実行されるにゃ</b>\")");
ex_411.push("setIntr(\"<b>今回は、継続条件式がa<=2だから、aが2以下の間が真なので、<br>今aには2が代入されているからもう一度文が実行されるにゃ</b>\")");
ex_411.push("setIntr(\"<b>文の実行が終わったらまた再初期化式を実行し～をくりかえし、<br>継続条件式に当てはまる間繰り返すにゃ。</b>\")");
ex_411.push("setIntr(\"<b>今回は2回繰り返したところで終わるようになってるにゃ</b>\")");
ex_411.push("setIntr(\"<b>これが「<font color=#ff0000>繰り返し</font>」というものにゃ</br>「繰り返し」のことを「<font color=#ff0000>ループ</font>」と言ったりするので<br>一応覚えておくといいにゃ</b>\")");
ex_411.push("setIntr(\"<b>まとめると<br>①初期化式を実行する</br>②継続条件式が満たされていたら文を実行する。<br>　満たされていなかったらfor文を抜け出す</br>③文を実行する\")");
ex_411.push("setIntr(\"<b>④文が終わったらfor文の1行目に戻り、再初期化式を実行する</br>⑤②～④を繰り返す</br>という感じにゃ!\")");
ex_411.push("setIntr(\"<b>再初期化式には<font color=#ff0000>++</font>がよく用いられるけど、<br><font color=#ff0000>--</font>でも、普通の数式でも可能にゃ！\")");
ex_411.push("setIntr(\"<b>2個目の「繰り返し」ではfor文の中身が変わっているけど<br>さっきと同じような動きをするにゃ</br>コードをよく読んでどういう動きになっているか想像するにゃ</b>\")");
ex_411.push("setIntr(\"<b>じゃあそれを踏まえてもう一度コードの動きを見るにゃ<br>コードの動きが複雑になってくるけど落ち着いて考えれば<br>大丈夫にゃ！\");;line_reset();;codeArrayInit();;sign=1;;baON()");

ex_411.push("baOFF();;line(3);;ANIME_changeSPEED_Ex(1.5);;ANIME_sengen(\"int\",\"a\");;line(4);;ANIME_sengen(\"int\",\"b\");;line(5);;ANIME_dainyu(\"a\",\"1\");;ANIME_compare([\"a<=2\"],[\"true\"],true);;line(6);;ANIME_printf(\"こん\\n\");;setPrintf(\"こん\\n\");;line(5);;ANIME_enzan_dainyu(\"a\",\"a+1\",\"2\");;ANIME_compare([\"a<=2\"],[\"true\"],true);;line(6);;ANIME_printf(\"こん\\n\");;setPrintf(\"こん\\n\");;line(5);;ANIME_enzan_dainyu(\"a\",\"a+1\",\"3\");;ANIME_compare([\"a<=2\"],[\"false\"],false);;line(8);;ANIME_dainyu(\"b\",\"2\");;ANIME_compare([\"b>=1\"],[\"true\"],true);;line(9);;ANIME_printf(\"たぬ\\n\");;setPrintf(\"たぬ\\n\");;line(8);;ANIME_enzan_dainyu(\"b\",\"b-1\",\"1\");;ANIME_compare([\"b>=1\"],[\"true\"],true);;line(9);;ANIME_printf(\"たぬ\\n\");;setPrintf(\"たぬ\\n\");;line(8);;ANIME_enzan_dainyu(\"b\",\"b-1\",\"0\");;ANIME_compare([\"b>=1\"],[\"false\"],false);;line(11);;setIntr(\"<b>なんとなくでもわかったら、次は自分で書いてみるにゃ！</b>\");;bRestart();;return_js()");

//---------------------------------------------

var ex_421 = new Array();
ex_421.push("setIntr(\"<b>これから見せるコードは、０を入力するまで数字の入力を<br>何度も受け付けるというプログラムにゃ</br>さっきまでと違って、何回繰り返すかはわからないコードだにゃ</br>じゃあコードを動かしてみるにゃ\");;baON()");

ex_421.push("baOFF();;line(3);;ANIME_sengen(\"int\",\"a\");;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"3\\n\");;ANIME_dainyu(\"a\",\"3\");;line(7);;ANIME_compare([\"a==0\"],[\"false\"],false);;line(11);;ANIME_printf(\"もう一度\");;setPrintf(\"もう一度\");;line_reset();;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"2\\n\");;ANIME_dainyu(\"a\",\"2\");;line(7);;ANIME_compare([\"a==0\"],[\"false\"],false);;line(11);;ANIME_printf(\"もう一度\");;setPrintf(\"もう一度\");;line_reset();;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"1\\n\");;ANIME_dainyu(\"a\",\"1\");;line(7);;ANIME_compare([\"a==0\"],[\"false\"],false);;line(11);;ANIME_printf(\"もう一度\");;setPrintf(\"もう一度\");;line_reset();;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"0\\n\");;ANIME_dainyu(\"a\",\"0\");;line(7);;ANIME_compare([\"a==0\"],[\"true\"],true);;line(8);;ANIME_printf(\"0が入力されたのでプログラムを終了します。\\n\");;setPrintf(\"0が入力されたのでプログラムを終了します。\\n\");;line(9);;line(13);;biON();;ANIME_changeSPEED_Ex(1);;setIntr(\"<b>じゃあ説明していくにゃ</b>\")");

ex_421.push("line_reset();;line(4);;setIntr(\"<b>まずは4～12行を見るにゃ、これが「<font color=#ff0000>while文</font>」にゃ</b>\")");
ex_421.push("setIntr(\"<b>while文はfor文と同じで<br>「繰り返し」のコードを書くことができるにゃ</b>\")");
ex_421.push("setIntr(\"<b>「()」で囲まれた部分が<font color=#ff0000>継続条件式</font>で</br>「｛｝」で囲まれた部分が<font color=#ff0000>文</font>にゃ</b>\")");
ex_421.push("setIntr(\"<b>forと同じで、継続条件式が満たされているあいだ<br>文を繰り返すことのできるコードにゃ</br>forと違うのは<font color=#ff0000>初期化式と再初期化式がない</font>所くらいにゃ</b>\")");
ex_421.push("setIntr(\"<b>今回、継続条件式には1と書かれているにゃ</br>プログラミングにおいて<font color=#ff0000>1は「真」を表す</font>にゃ<br>つまり、継続条件式が満たされていることになるにゃ</br>ちなみにプログラミングにおいて<font color=#ff0000>「0」は偽</font>、<br>つまり満たされないことになるから覚えておく<br>にゃ</b>\")");
ex_421.push("setIntr(\"<b>こうすることで継続条件式が常に満たされていることになり、<br>永遠にwhile文の中を繰り返すことができるようになってるにゃ</br>\")");
ex_421.push("setIntr(\"<b>あと、このように永遠に繰り返す構造のことを「<font color=#ff0000>無限ループ</font>」と言ったりするので一応覚えておくにゃ</b>\")");
ex_421.push("setIntr(\"<b>え？永遠に続くなら終わらないんじゃにゃいかって？</br>その通りにゃ<br>「無限ループ」になってしまうとコードが終わらないので</br>「繰り返し」を使う際は気を付けなければならないにゃ</b>\")");
ex_421.push("setIntr(\"<b>じゃあなんで、今回はちゃんと終わらせることができたかというと</br>9行目にある「<font color=#ff0000>break</font>」というコードのおかげにゃ</b>\")");
ex_421.push("line(9);;setIntr(\"<b>このbreakが実行されると、<br>ループを一つ抜け出すことができるにゃ</br>今回はwhileの中にあるので、<br>このwhileを抜け出すことができるにゃ</b>\")");
ex_421.push("setIntr(\"<b>breakはループの中にif文を書いて、その中に書くことが多いにゃ</br>今回は0が入力されるとif文が実行される構造になっているので、</br>0が入力されることでbreakが実行されて無限ループを抜け出して、コードを終わらせることができるにゃ\")");
ex_421.push("setIntr(\"<b>じゃあもう一度コードの動きを見るにゃ<br>さっきと同じように入力は3，2，1，0にゃ\");;line_reset();;codeArrayInit();;sign=1;;baON()");

ex_421.push("baOFF();;line(3);;ANIME_sengen(\"int\",\"a\");;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"3\\n\");;ANIME_dainyu(\"a\",\"3\");;line(7);;ANIME_compare([\"a==0\"],[\"false\"],false);;line(11);;ANIME_printf(\"もう一度\");;setPrintf(\"もう一度\");;line_reset();;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"2\\n\");;ANIME_dainyu(\"a\",\"2\");;line(7);;ANIME_compare([\"a==0\"],[\"false\"],false);;line(11);;ANIME_printf(\"もう一度\");;setPrintf(\"もう一度\");;line_reset();;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"1\\n\");;ANIME_dainyu(\"a\",\"1\");;line(7);;ANIME_compare([\"a==0\"],[\"false\"],false);;line(11);;ANIME_printf(\"もう一度\");;setPrintf(\"もう一度\");;line_reset();;line(4);;ANIME_compare([\"1\"],[\"1\"],1);;line(5);;ANIME_printf(\"数字を入力してください:\");;setPrintf(\"数字を入力してください:\");;line(6);;ANIME_scanf_ex();;setPrintf(\"0\\n\");;ANIME_dainyu(\"a\",\"0\");;line(7);;ANIME_compare([\"a==0\"],[\"true\"],true);;line(8);;ANIME_printf(\"0が入力されたのでプログラムを終了します。\\n\");;setPrintf(\"0が入力されたのでプログラムを終了します。\\n\");;line(9);;line(13);;biON();;ANIME_changeSPEED_Ex(1);;setIntr(\"<b>わかったかにゃ？\")");

ex_421.push("line_reset();;setIntr(\"<b>ちなみにfor文でもwhile文でも<br>同じ動きのコードを書くことができるにゃ</br>なんで二つの書き方があるかというと、<br>それぞれ得意分野があるにゃ</b>\")");
ex_421.push("setIntr(\"<b>for文は今までやってきたような、<br>何回繰り返されるかわかっている場合が得意で、</br>while文は、何回繰り返されるかわからないときが得意にゃ</br>どっちで書いても問題ないけど、<br>こういった特性を覚えておくと便利にゃ</b>\")");
ex_421.push("setIntr(\"<b>じゃあ、whileの使い方を問題を解いて練習していくにゃ！\");;bRestart();;return_js()");

//---------------------------------------------

var ex_431 = new Array();
ex_431.push("setIntr(\"<b>これから見せるコードは、<br>「＊」を2個ずつ書いたものを3行作るコードにゃ</br>まずは動きを見るにゃ、複雑な動きをするからよく見ておくにゃ\");;baON()");

ex_431.push("baOFF();;line(3);;ANIME_sengen(\"int\",\"i\");;ANIME_sengen(\"int\",\"k\");;line(4);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(5);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<2\"],[\"false\"],false);;line(8);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(4);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(5);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<2\"],[\"false\"],false);;line(8);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(4);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(5);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<2\"],[\"false\"],false);;line(8);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");; line(4);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(10);;ANIME_changeSPEED_Ex(1);;setIntr(\"<b>じゃあ説明していくにゃ</b>\");;biON()");

ex_431.push("line_reset();;line(4);;setIntr(\"<b>まずは、4，5行目を見るにゃ</br>for文の中にfor文が入っているのがわかるかにゃ？\")");
ex_431.push("setIntr(\"<b>今回みたいに、「*」を出力を2回繰り返し、<br>それを3行分だから3回繰り返す、のように、<br><font color=#ff0000>繰り返すものを繰り返したい時</font>に、このような<br><font color=#ff0000>for文の中にfor文を入れる</font>コードを書くにゃ</b>\")");
ex_431.push("setIntr(\"<b>このようにfor文の中にfor文を入れることを<br>「<font color=#ff0000>二重ループ</font>」っていうにゃ</b>\")");
ex_431.push("setIntr(\"<b>まず、一つ目のfor文で3回繰り返すようにしてるにゃ</br>これが3行にするためのループだにゃ</b>\")");
ex_431.push("line(5);;setIntr(\"<b>そしてその中に「*」を2回繰り返すfor文を書いてるにゃ</br>これで2個「*」が出力できるにゃ</b>\")");
ex_431.push("line(8);;setIntr(\"<b>そして2個「*」を出力したら内側にあるループを抜けて、<br>ここで一回改行してるにゃ</b>\")");
ex_431.push("setIntr(\"<b>改行したら一つ目ののループの「}」につくので、<br>上に戻ってまた繰り返すにゃ</b>\")");
ex_431.push("setIntr(\"<b>少し複雑な動きだけどついてこれてるかにゃ?</br>今の話を踏まえてもう一度動きを見てみるにゃ</b>\");;line_reset();;codeArrayInit();;sign=1;;baON()");

ex_431.push("baOFF();;line(3);;ANIME_sengen(\"int\",\"i\");;ANIME_sengen(\"int\",\"k\");;line(4);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(5);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<2\"],[\"false\"],false);;line(8);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(4);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(5);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<2\"],[\"false\"],false);;line(8);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(4);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(5);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<2\"],[\"true\"],true);;line(6);;ANIME_printf(\"*\");;setPrintf(\"*\");;line(5);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<2\"],[\"false\"],false);;line(8);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");; line(4);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(10);;ANIME_changeSPEED_Ex(1);;setIntr(\"<b>わかったかにゃ？ちょっと難しいけど踏ん張りどころにゃ！</br>じゃあ問題を解いて練習するにゃ!</b>\");;bRestart();;return_js()");

//---------------------------------------------

var ex_511 = new Array();
ex_511.push("setIntr(\"<b>今回は「配列」というものを学んでいくにゃ</br>まずはコードの動きを見るにゃ</b>\");;baON()");

ex_511.push("baOFF();;line(3);;ANIME_array_sengen_dainyu(\"int\",\"a\",3,[\"2\",\"6\",\"3\"],[\"2\",\"6\",\"3\"]);;line(4);;ANIME_sengen(\"int\",\"i\");;line(5);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[0]\"]);;setPrintf(\"a[0] = 2\\n\");;;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[1]\"]);;setPrintf(\"a[1] = 6\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[2]\"]);;setPrintf(\"a[2] = 3\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(8);;ANIME_changeSPEED_Ex(1);;biON();;setIntr(\"<b>じゃあ説明していくにゃ</b>\")");

ex_511.push("line_reset();;setIntr(\"<b>電車みたいなものが出てきたのは気づいたかにゃ？</br>この電車が「<font color=#ff0000>配列</font>」というもので、<br>車両一つ一つが変数のようなものにゃ</b>\")");
ex_511.push("line(3);;setIntr(\"<b>コードの3行目を見るにゃ。<br>このコードで配列を宣言および初期化をしてるにゃ</br>配列というのは、変数の仲間の一つだにゃ</b>\")");
ex_511.push("setIntr(\"<b>int aなので、とりあえず今まで見てきた部分はそのままで、</br>int型でaという名前の変数を宣言しているのはわかるかにゃ?</b>\")");
ex_511.push("setIntr(\"<b>そして名前の後ろに[3]というのがついてるにゃ。</br>配列というのは、同じデータ型の変数を<br>いくつかつなげたようなもので、</br>この[3]というので<font color=#ff0000>つなげる数</font>を決めてるにゃ</b>\")");
ex_511.push("setIntr(\"<b>今回は[3]なので3つつなげてるにゃ</br>つまり、int a[3]で、「aという名前の大きさが3の配列を宣言」しているということだにゃ</b>\")");
ex_511.push("setIntr(\"<b>そして、その後ろのコードで配列を初期化してるにゃ</br>この、配列内の各数字のことを「<font color=#ff0000>配列の要素</font>」というにゃ</b>\")");
ex_511.push("setIntr(\"<b>配列を初期化するときは、こんなふうに<br><font color=#ff0000>｛｝</font>に入れたい数字を順番に書いていくにゃ</b>\")");
ex_511.push("setIntr(\"<b>じゃあもう一度動きを見てみるにゃ</b>\");;line_reset();;codeArrayInit();;sign=1;;baON()");

ex_511.push("baOFF();;line(3);;ANIME_array_sengen_dainyu(\"int\",\"a\",3,[\"2\",\"6\",\"3\"],[\"2\",\"6\",\"3\"]);;line(4);;ANIME_sengen(\"int\",\"i\");;line(5);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[0]\"]);;setPrintf(\"a[0] = 2\\n\");;;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[1]\"]);;setPrintf(\"a[1] = 6\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[2]\"]);;setPrintf(\"a[2] = 3\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(8);;ANIME_changeSPEED_Ex(1);;biON();;setIntr(\"<b>どうかにゃ？</br>よくわからなかったらもう一度動きを見るにゃ。</b>\")");

ex_511.push("setIntr(\"<b>いつもならこの後は問題だけど、今回はもう一度別の例題を見てほしいので、次に進んでまた別の説明を聞いてほしいにゃ</br>\");;bRestart();;return_js3()");

//---------------------------------------------

var ex_512 = new Array();
ex_512.push("setIntr(\"<b>ということで、今回は続けて説明だにゃ！</br>難しいところなので、我慢して聞いてほしいにゃ</b>\");;baON()");

ex_512.push("baOFF();;line(3);;ANIME_array_sengen(\"int\",\"a\",\"3\");;line(4);;ANIME_sengen(\"int\",\"i\");;line(5);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_scanf_ex();;setPrintf(\"0\\n\");;ANIME_array_dainyu(\"a[0]\",\"0\");;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_scanf_ex();;setPrintf(\"1\\n\");;ANIME_array_dainyu(\"a[1]\",\"1\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_scanf_ex();;setPrintf(\"2\\n\");;ANIME_array_dainyu(\"a[2]\",\"2\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(8);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(9);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[0]\"]);;setPrintf(\"a[0] = 0\\n\");;line(8);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(9);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[1]\"]);;setPrintf(\"a[1] = 1\\n\");;line(8);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(9);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[2]\"]);;setPrintf(\"a[2] = 2\\n\");;line(8);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(11);;ANIME_changeSPEED_Ex(1);;biON();;setIntr(\"<b>じゃあ説明するにゃ</b>\")");

ex_512.push("line_reset();;setIntr(\"<b>さっきは配列の宣言および初期化の仕方について教えたにゃ</br>今回は、配列の扱い方について説明するにゃ</b>\")");
ex_512.push("line_reset();;setIntr(\"<b>扱い方っていうのは、printfとかscanfで配列を使うときは<br>どうやって使うかってことにゃ</b>\")");
ex_512.push("line(3);;setIntr(\"<b>まずは3行目だにゃ</br>ここで、配列を宣言してるのはわかるかにゃ？</br>今回は「aという名前の大きさが5の配列を宣言」しているにゃ</b>\")")
ex_512.push("setIntr(\"<b>今回は宣言のみで初期化は行ってないにゃ</br>なので、あとから代入していくにゃ</b>\")");
ex_512.push("line(6);;setIntr(\"<b>5~7行目を見るにゃ</br>ここで、scanfを使ってキーボードから配列に代入してるにゃ</br>scanfの中の<font color=#ff0000>a[i]</font>というのが分かるかにゃ?これで配列の一か所だけを呼ぶことができるにゃ</b>\")");
ex_512.push("setIntr(\"<b>ここで注意してほしいことがあるにゃ</br>配列の先頭は「1番目」じゃなくて「<font color=#ff0000>０番目</font>」ということにゃ</b>\")");
ex_512.push("setIntr(\"<b>つまり、配列の一番最初に1を代入したい時は、<br>a[0]=1　みたいに書くにゃ</br>ちなみに配列に好きな数字を代入していく場合、<br>for文を使うと便利にゃ</b>\")");
ex_512.push("setIntr(\"<b>そして8～10行目を見るにゃ</br>さっきと同じように配列の中身を1個だけ呼ぶ場合は<br>a[0]とかa[1]で呼ぶにゃ</br>で、printfで呼ぶ場合は今まで通り、int型だから％dで呼ぶにゃ</b>\")");
ex_512.push("setIntr(\"<b>じゃあここまでを踏まえてもう一度動きを見るにゃ</b>\");;line_reset();;codeArrayInit();;sign=1;;baON()");

ex_512.push("baOFF();;line(3);;ANIME_array_sengen(\"int\",\"a\",\"3\");;line(4);;ANIME_sengen(\"int\",\"i\");;line(5);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_scanf_ex();;setPrintf(\"0\\n\");;ANIME_array_dainyu(\"a[0]\",\"0\");;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(2);;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_scanf_ex();;setPrintf(\"1\\n\");;ANIME_array_dainyu(\"a[1]\",\"1\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_scanf_ex();;setPrintf(\"2\\n\");;ANIME_array_dainyu(\"a[2]\",\"2\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(8);;ANIME_dainyu(\"i\",\"0\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(9);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[0]\"]);;setPrintf(\"a[0] = 0\\n\");;line(8);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(9);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[1]\"]);;setPrintf(\"a[1] = 1\\n\");;line(8);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;ANIME_compare([\"i<3\"],[\"true\"],true);;line(9);;ANIME_printf([\"a[\",\"%d\",\"] = \",\"%d\",\"\\n\"],[\"i\",\"a[2]\"]);;setPrintf(\"a[2] = 2\\n\");;line(8);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;ANIME_compare([\"i<3\"],[\"false\"],false);;line(11);;ANIME_changeSPEED_Ex(1);;setIntr(\"<b>どうかにゃ？宣言や扱い方はわかったかにゃ？</br>じゃあ問題に行くにゃ！。</b>\");;bRestart();;return_js()");

//---------------------------------------------

var ex_521 = new Array();
ex_521.push("setIntr(\"<b>つぎは「<font color=#ff0000>二次元配列</font>」というものを学んでいくにゃ</br>配列の進化系って感じかにゃ</br>まずは動きを見るにゃ</b>\");;baON()");

ex_521.push("baOFF();;line(3);;ANIME_sengen(\"int\",\"i\");;ANIME_sengen(\"int\",\"k\");;line(4);;ANIME_twoDarray_sengen_dainyu(\"int\",\"data\",3,3,[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"],[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"]);;line(5);;ANIME_dainyu(\"i\",\"0\");;;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[0][0]\"]);;setPrintf(\"1\");;line(6);;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(3);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;line(7);;ANIME_printf([\"%d\"],[\"data[0][1]\"]);;setPrintf(\"2\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[0][2]\"]);;setPrintf(\"3\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"3\");;ANIME_compare([\"k<3\"],[\"false\"],false);;line(9);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[1][0]\"]);;setPrintf(\"4\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[1][1]\"]);;setPrintf(\"5\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[1][2]\"]);;setPrintf(\"6\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"3\");;ANIME_compare([\"k<3\"],[\"false\"],false);;line(9);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[2][0]\"]);;setPrintf(\"7\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[2][1]\"]);;setPrintf(\"8\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[2][2]\"]);;setPrintf(\"9\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"3\");;ANIME_compare([\"k<3\"],[\"false\"],false);;line(9);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;;ANIME_compare([\"i<3\"],[\"false\"],false);;line(11);;ANIME_changeSPEED_Ex(1);;biON();;setIntr(\"<b>じゃあ説明していくにゃ</b>\")");

ex_521.push("line_reset();;setIntr(\"<b>電車の形が少し変わってるのには気づいたかにゃ？</br>これが二次元配列だにゃ</b>\")");
ex_521.push("setIntr(\"<b>まず言葉で説明すると、</br>二次元配列というのは、配列を要素として持ってる配列だにゃ</br>なんとなくわかるかにゃ？</b>\")");
ex_521.push("line(3);;setIntr(\"<b>じゃあコードの3行目を見るにゃ</br>この部分で「dataという名前の二次元配列を宣言」してるにゃ</br>さっきまでの配列の宣言と違うのは<br>名前の後の大きさの指定のところにゃ</b>\")");
ex_521.push("setIntr(\"<b>[3][3]なので、この場合は大きさが[3]の配列を<br>要素として「3つ」持つ配列だにゃ</br>[2][3]だったら、大きさが[3]の配列を<br>要素として「2つ」持つ配列という感じにゃ</b>\")");
ex_521.push("setIntr(\"<b>二次元配列を初期化する場合は<font color=#ff0000>{{数字},{数字},{数字}}</font><br>のような感じで初期化するにゃ</br>よく見て書き方も覚えておくにゃ</br>間違いやすいので、辞書もちゃんと見るといいにゃ</b>\")");
ex_521.push("setIntr(\"<b>次は6行目を見るにゃ</br>二次元配列の扱い方は<font color=#ff0000>a[数字][数字]</font>で呼び出すにゃ</br>今までの配列と同じ様に、一番最初は０なので注意するにゃ</b>\")");
ex_521.push("setIntr(\"<b>だから、「二次元配列内の、最初の配列の、<br>最初の要素を呼び出す」場合はa[0][0]で呼び出すにゃ</b>\")");
ex_521.push("setIntr(\"<b>これが二次元配列だにゃ</br>呼び出したりするときに混乱しやすいので落ち着いて判断するにゃ</b>\")");
ex_521.push("setIntr(\"<b>じゃあもう一度コードの動きを見るにゃ\");;line_reset();;codeArrayInit();;sign=1;;baON()");

ex_521.push("baOFF();;line(3);;ANIME_sengen(\"int\",\"i\");;ANIME_sengen(\"int\",\"k\");;line(4);;ANIME_twoDarray_sengen_dainyu(\"int\",\"data\",3,3,[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"],[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"]);;line(5);;ANIME_dainyu(\"i\",\"0\");;;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[0][0]\"]);;setPrintf(\"1\");;line(6);;setIntr(\"<b>ここからは早送りするにゃ</b>\");;ANIME_changeSPEED_Ex(3);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;line(7);;ANIME_printf([\"%d\"],[\"data[0][1]\"]);;setPrintf(\"2\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[0][2]\"]);;setPrintf(\"3\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"3\");;ANIME_compare([\"k<3\"],[\"false\"],false);;line(9);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"1\");;;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[1][0]\"]);;setPrintf(\"4\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[1][1]\"]);;setPrintf(\"5\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[1][2]\"]);;setPrintf(\"6\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"3\");;ANIME_compare([\"k<3\"],[\"false\"],false);;line(9);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"2\");;;ANIME_compare([\"i<3\"],[\"true\"],true);;line(6);;ANIME_dainyu(\"k\",\"0\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[2][0]\"]);;setPrintf(\"7\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"1\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[2][1]\"]);;setPrintf(\"8\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"2\");;ANIME_compare([\"k<3\"],[\"true\"],true);;line(7);;ANIME_printf([\"%d\"],[\"data[2][2]\"]);;setPrintf(\"9\");;line(6);;ANIME_enzan_dainyu(\"k\",\"k+1\",\"3\");;ANIME_compare([\"k<3\"],[\"false\"],false);;line(9);;ANIME_printf(\"\\n\");;setPrintf(\"\\n\");;line(5);;ANIME_enzan_dainyu(\"i\",\"i+1\",\"3\");;;ANIME_compare([\"i<3\"],[\"false\"],false);;line(11);;ANIME_changeSPEED_Ex(1);;setIntr(\"<b>じゃあいよいよ問題にゃ！</br>がんばるにゃ！</b>\");;bRestart();;return_js()");
